apiVersion: v1
kind: Namespace
metadata:
  name: plex
  labels:
    k10.kasten.io/backup: "true"
    storage-class: longhorn
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: baseline
