apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-credentials
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: external-dns-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: SECRET_EXTERNAL_DNS_KERBEROS_USERNAME
    - secretKey: password
      remoteRef:
        key: SECRET_EXTERNAL_DNS_KERBEROS_PASSWORD
    - secretKey: rfc2136-host
      remoteRef:
        key: SECRET_EXTERNAL_DNS_RFC2136_HOST
    - secretKey: domain
      remoteRef:
        key: SECRET_DOMAIN
    - secretKey: kerberos-realm
      remoteRef:
        key: SECRET_EXTERNAL_DNS_KERBEROS_REALM
