apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-test-config-vsan
  namespace: plex-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsan
  resources:
    requests:
      storage: 30Gi
