---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-db-credentials
  namespace: sonarr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: sonarr-db-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: sonarr
        password: "{{ .dbPassword }}"
  data:
    - secretKey: dbPassword
      remoteRef:
        key: SECRET_SONARR_POSTGRES_PASSWORD
