---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: guacamole
  namespace: guacamole
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      guacamole:
        containers:
          app:
            image:
              repository: guacamole/guacamole
              tag: "1.6.0"
            env:
              GUACD_HOSTNAME: guacamole-guacd
              GUACD_PORT: "4822"
              GUACAMOLE_HOME: /etc/guacamole/
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /guacamole/
                    port: 8080
                  initialDelaySeconds: 45
                  timeoutSeconds: 10
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /guacamole/
                    port: 8080
                  initialDelaySeconds: 2
                  timeoutSeconds: 10
      guacd:
        containers:
          app:
            image:
              repository: guacamole/guacd
              tag: "1.6.0"

    service:
      app:
        controller: guacamole
        ports:
          http:
            port: 8080
      guacd:
        controller: guacd
        ports:
          guacd:
            port: 4822

    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |
            conditions: ["[STATUS] < 500"]
            interval: 60s
            group: tools
        hostnames:
          - "guac.${SECRET_DOMAIN}"
        parentRefs:
          - name: main
            namespace: cilium
            sectionName: https
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            filters:
              - type: URLRewrite
                urlRewrite:
                  path:
                    type: ReplacePrefixMatch
                    replacePrefixMatch: /guacamole
            backendRefs:
              - identifier: app
                port: http

    configMaps:
      root-redirect:
        enabled: true
        data:
          index.jsp: |
            <% response.sendRedirect("/guacamole"); %>

    persistence:
      guacamole-conf:
        type: secret
        name: guacamole-user-mapping
        advancedMounts:
          guacamole:
            app:
              - path: /etc/guacamole/
      root-redirect:
        type: configMap
        name: guacamole-root-redirect
        advancedMounts:
          guacamole:
            app:
              - path: /usr/local/tomcat/webapps/ROOT/index.jsp
                subPath: index.jsp
                readOnly: true
