---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr-secrets
  namespace: recyclarr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: recyclarr-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: SONARR_NL_API_KEY
      remoteRef:
        key: SECRET_SONARR_NL_API_KEY
