---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-widgets
  namespace: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: homepage-widgets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: HOMEPAGE_VAR_SONARR
      remoteRef:
        key: SECRET_SONARR_API_KEY
    - secretKey: HOMEPAGE_VAR_SONARR_NL
      remoteRef:
        key: SECRET_SONARR_NL_API_KEY
    - secretKey: HOMEPAGE_VAR_RADARR
      remoteRef:
        key: SECRET_RADARR_API_KEY
    - secretKey: HOMEPAGE_VAR_BAZARR
      remoteRef:
        key: SECRET_BAZARR_API_KEY
    - secretKey: HOMEPAGE_VAR_PROWLARR
      remoteRef:
        key: SECRET_PROWLARR_API_KEY
    - secretKey: HOMEPAGE_VAR_SAB
      remoteRef:
        key: SECRET_SAB_API_KEY
    - secretKey: HOMEPAGE_VAR_TAUTULLI
      remoteRef:
        key: SECRET_TAUTULLI_API_KEY
    - secretKey: HOMEPAGE_VAR_OMBI
      remoteRef:
        key: SECRET_OMBI_API_KEY
    - secretKey: HOMEPAGE_VAR_PLEX
      remoteRef:
        key: SECRET_PLEX_TOKEN
    - secretKey: HOMEPAGE_VAR_TDARR
      remoteRef:
        key: SECRET_TDARR_API_KEY
    - secretKey: HOMEPAGE_VAR_NZBGET
      remoteRef:
        key: SECRET_NZBGET_PASSWORD
