---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-widgets
  namespace: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: homepage-widgets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: HOMEPAGE_VAR_SONARR
      remoteRef:
        key: SECRET_SONARR_API_KEY
    - secretKey: HOMEPAGE_VAR_SONARR_NL
      remoteRef:
        key: SECRET_SONARR_NL_API_KEY
    - secretKey: HOMEPAGE_VAR_RADARR
      remoteRef:
        key: SECRET_RADARR_API_KEY
    - secretKey: HOMEPAGE_VAR_BAZARR
      remoteRef:
        key: SECRET_BAZARR_API_KEY
    - secretKey: HOMEPAGE_VAR_PROWLARR
      remoteRef:
        key: SECRET_PROWLARR_API_KEY
    - secretKey: HOMEPAGE_VAR_SAB
      remoteRef:
        key: SECRET_SAB_API_KEY
    - secretKey: HOMEPAGE_VAR_TAUTULLI
      remoteRef:
        key: SECRET_TAUTULLI_API_KEY
    - secretKey: HOMEPAGE_VAR_OMBI
      remoteRef:
        key: SECRET_OMBI_API_KEY
    - secretKey: HOMEPAGE_VAR_PLEX
      remoteRef:
        key: SECRET_PLEX_TOKEN
    - secretKey: HOMEPAGE_VAR_TRACEARR
      remoteRef:
        key: SECRET_HOMEPAGE_TRACEARR
    - secretKey: HOMEPAGE_VAR_TDARR
      remoteRef:
        key: SECRET_TDARR_API_KEY
    - secretKey: HOMEPAGE_VAR_NZBGET
      remoteRef:
        key: SECRET_NZBGET_PASSWORD
    - secretKey: HOMEPAGE_VAR_OPNSENSE_KEY
      remoteRef:
        key: SECRET_OPNSENSE_API_KEY
    - secretKey: HOMEPAGE_VAR_OPNSENSE_SECRET
      remoteRef:
        key: SECRET_OPNSENSE_API_SECRET
    - secretKey: HOMEPAGE_VAR_MIKROTIK
      remoteRef:
        key: SECRET_MIKROTIK_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-extras
  namespace: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: homepage-extras
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: TRUENAS_TOKEN
      remoteRef:
        key: SECRET_TRUENAS_API_KEY
    - secretKey: VSPHERE_USER
      remoteRef:
        key: SECRET_VSPHERE_USERNAME
    - secretKey: VSPHERE_PASS
      remoteRef:
        key: SECRET_VSPHERE_PASSWORD
    - secretKey: ESXI_PASSWORD
      remoteRef:
        key: SECRET_ESXI_ROOT_PASSWORD
