---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - namespace.yaml
  - externalsecret.yaml
  - configmap.yaml
  - sidecar-configmap.yaml
  - helmrelease.yaml
  - tunnelbinding.yaml
