apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k10-secrets
  namespace: kasten-io
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: k10-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        vsphere-username: "{{ .vsphereUsername }}"
        vsphere-password: "{{ .vspherePassword }}"
        bindPW: "{{ .ldapBindPW }}"
  data:
    - secretKey: vsphereUsername
      remoteRef:
        key: SECRET_VSPHERE_USERNAME
    - secretKey: vspherePassword
      remoteRef:
        key: SECRET_VSPHERE_PASSWORD
    - secretKey: ldapBindPW
      remoteRef:
        key: SECRET_EXTERNAL_DNS_KERBEROS_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k10-b2-creds
  namespace: kasten-io
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: k10-b2-creds
    creationPolicy: Owner
    template:
      type: secrets.kanister.io/aws
      data:
        aws_access_key_id: "{{ .keyId }}"
        aws_secret_access_key: "{{ .appKey }}"
  data:
    - secretKey: keyId
      remoteRef:
        key: SECRET_BACKBLAZE_B2_KEY_ID
    - secretKey: appKey
      remoteRef:
        key: SECRET_BACKBLAZE_B2_APP_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k10-vsphere-creds
  namespace: kasten-io
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: k10-vsphere-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        vsphere_user: "{{ .user }}"
        vsphere_password: "{{ .password }}"
  data:
    - secretKey: user
      remoteRef:
        key: SECRET_VSPHERE_USERNAME
    - secretKey: password
      remoteRef:
        key: SECRET_VSPHERE_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8s-app-backup-migration-token
  namespace: kasten-io
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: k8s-app-backup-migration-token
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        migrationToken: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: SECRET_KASTEN_MIGRATION_TOKEN
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k10-dr-secret
  namespace: kasten-io
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: k10-dr-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        key: "{{ .passphrase }}"
  data:
    - secretKey: passphrase
      remoteRef:
        key: SECRET_KASTEN_DR_PASSPHRASE
