apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ad-ca-configmap.yaml
  - externalsecret.yaml
  - helmrelease.yaml
  - httproute.yaml
  - clusterrolebinding.yaml
  - vbr-integration.yaml
  - profile-backblaze.yaml
  - profile-vsphere.yaml
  - policypreset-k8s-backup.yaml
  - policy-k8s-backup.yaml
  - policypreset-k8s-gpu-backup.yaml
  - policy-k8s-gpu-backup.yaml
  - policy-dr.yaml
