apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: k8s-backup
  namespace: kasten-io
spec:
  presetRef:
    name: k8s-backup
    namespace: kasten-io
  selector:
    matchLabels:
      storage-class: vsphere
  actions:
    - action: backup
      backupParameters:
        filters:
          excludeResources:
            - name: sabnzbd-download
    - action: export
