apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: k8s-app-backup
  namespace: kasten-io
spec:
  paused: true
  presetRef:
    name: k8s-app-backup
    namespace: kasten-io
  selector:
    matchLabels:
      k10.kasten.io/backup: "true"
  actions:
    - action: backup
      backupParameters:
        filters:
          excludeResources:
            - name: sabnzbd-download
    - action: export
      exportParameters:
        migrationToken:
          name: k8s-app-backup-migration-token
          namespace: kasten-io
        receiveString: ${SECRET_KASTEN_MIGRATION_TOKEN}
