apiVersion: config.kio.kasten.io/v1alpha1
kind: PolicyPreset
metadata:
  name: k8s-backup
  namespace: kasten-io
spec:
  backup:
    frequency: '@daily'
    retention: {}
    subFrequency:
      days: [1]
      hours: [5]
      minutes: [0]
      months: [1]
      weekdays: [0]
  export:
    profile:
      name: backblaze
      namespace: kasten-io
    blockModeProfile:
      name: backblaze
      namespace: kasten-io
    exportData:
      enabled: true
    retention:
      daily: 7
      weekly: 4
