apiVersion: config.kio.kasten.io/v1alpha1
kind: Profile
metadata:
  name: backblaze-b2
  namespace: kasten-io
spec:
  type: Location
  locationSpec:
    credential:
      secretType: AwsAccessKey
      secret:
        apiVersion: v1
        kind: secret
        name: k10-b2-creds
        namespace: kasten-io
    type: ObjectStore
    objectStore:
      endpoint: s3.eu-central-003.backblazeb2.com
      name: skw-kasten
      objectStoreType: S3
      path: k10/8cb2567f-26cf-4038-879c-d4dea2574df7/migration
      pathType: Directory
      region: eu-central-003
