apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - be-stream-downloader/ks.yaml
  - media-toolkit/ks.yaml
  - ombi/ks.yaml
  - plex/ks.yaml
  - plex-test/ks.yaml
  - tautulli/ks.yaml
  - tdarr/ks.yaml
  - tracearr/ks.yaml
  - whisper-asr/ks.yaml
