apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - belgian-dl/ks.yaml
  - clusterplex/ks.yaml
  - ombi/ks.yaml
  - plex/ks.yaml
  - tautulli/ks.yaml
  - tdarr/ks.yaml
  - tracearr/ks.yaml
