---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gpu-node-vsphere-maintenance-controller
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/varashi/charts/gpu-node-vsphere-maintenance-controller
  ref:
    tag: 0.4.4
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: ^https://token\.actions\.githubusercontent\.com$
        subject: ^https://github\.com/Varashi/gpu-node-vsphere-maintenance-controller/\.github/workflows/release\.yaml@refs/tags/.*$
