---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kube-logging
  namespace: flux-system
spec:
  type: oci
  url: oci://ghcr.io/kube-logging/helm-charts
  interval: 1h
