---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium.yaml
  - cert-manager.yaml
  - external-secrets.yaml
  - bitwarden-sdk-server.yaml
  - bjw-s.yaml
  - kubelet-csr-approver.yaml
  - external-dns.yaml
  - cloudflare-operator.yaml
  - metrics-server.yaml
  - vsphere-cpi.yaml
  - kasten.yaml
  - cnpg.yaml
  - netbox.yaml
  - node-feature-discovery.yaml
  - intel-device-plugins.yaml
  - longhorn.yaml
  - prometheus-community.yaml
  - descheduler.yaml
  - stakater.yaml
  - fluent.yaml
  - gpu-node-vsphere-maintenance-controller.yaml
