apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: guacamole-user-mapping
  namespace: guacamole
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: guacamole-user-mapping
    creationPolicy: Owner
  data:
    - secretKey: user-mapping.xml
      remoteRef:
        key: SECRET_GUACAMOLE_USER_MAPPING
