---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-root-redirect
  namespace: guacamole
data:
  index.jsp: |
    <% response.sendRedirect("/guacamole"); %>
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole-svc
  namespace: guacamole
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: guacamole
---
apiVersion: v1
kind: Service
metadata:
  name: guacd-svc
  namespace: guacamole
spec:
  ports:
    - port: 4822
      protocol: TCP
  selector:
    run: guacd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      run: guacamole
  template:
    metadata:
      labels:
        run: guacamole
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: intel.feature.node.kubernetes.io/gpu
                    operator: DoesNotExist
      tolerations:
        - key: node.cloudprovider.kubernetes.io/uninitialized
          operator: Exists
          effect: NoSchedule
      containers:
        - name: guacamole
          image: guacamole/guacamole:1.6.0
          env:
            - name: GUACD_HOSTNAME
              value: guacd-svc.guacamole
            - name: GUACD_PORT
              value: "4822"
            - name: GUACAMOLE_HOME
              value: /etc/guacamole/
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: guacamole-conf
              mountPath: /etc/guacamole/
            - name: guacamole-root-redirect
              mountPath: /usr/local/tomcat/webapps/ROOT/index.jsp
              subPath: index.jsp
              readOnly: true
          livenessProbe:
            httpGet:
              path: /guacamole/
              port: 8080
            initialDelaySeconds: 45
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /guacamole/
              port: 8080
            initialDelaySeconds: 2
            timeoutSeconds: 10
      volumes:
        - name: guacamole-conf
          secret:
            secretName: guacamole-user-mapping
        - name: guacamole-root-redirect
          configMap:
            name: guacamole-root-redirect
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      run: guacd
  template:
    metadata:
      labels:
        run: guacd
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: intel.feature.node.kubernetes.io/gpu
                    operator: DoesNotExist
      tolerations:
        - key: node.cloudprovider.kubernetes.io/uninitialized
          operator: Exists
          effect: NoSchedule
      containers:
        - name: guacd
          image: guacamole/guacd:1.6.0
          ports:
            - containerPort: 4822
