apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gatus/ks.yaml
  - guacamole/ks.yaml
  - netbox/ks.yaml
  - ocis/ks.yaml
  - octodns/ks.yaml
  - postfix-relay/ks.yaml
  - rustdesk/ks.yaml
