---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: neutarr
  namespace: neutarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: intel.feature.node.kubernetes.io/gpu
                    operator: DoesNotExist
      tolerations:
        - key: node.cloudprovider.kubernetes.io/uninitialized
          operator: Exists
          effect: NoSchedule
      securityContext:
        runAsUser: 0
        runAsGroup: 0
    controllers:
      neutarr:
        containers:
          app:
            image:
              repository: iampuid0/neutarr
              tag: latest
              pullPolicy: Always
            env:
              TZ: Europe/Brussels
    service:
      app:
        controller: neutarr
        ports:
          http:
            port: 9705
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |
            conditions: ["[STATUS] < 500"]
            interval: 60s
            group: arr
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Neutarr
          gethomepage.dev/description: Missing/upgrade hunter
          gethomepage.dev/group: Arr
          gethomepage.dev/weight: "50"
          gethomepage.dev/icon: mdi-neutron
          gethomepage.dev/href: https://neutarr.${SECRET_DOMAIN}
        hostnames:
          - neutarr.${SECRET_DOMAIN}
        parentRefs:
          - name: main
            namespace: cilium
            sectionName: https
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: app
                port: http
    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: neutarr
        globalMounts:
          - path: /config
