apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Workloads will be added here during migration from k8s/RKE2
resources:
  - autobrr
  - bazarr
  - clusterplex
  - guacamole
  - home-assistant
  - netbox
  - neutarr
  - nzbget
  - nzbget-test
  - ocis
  - ombi
  - plex
  - postfix-relay
  - prowlarr
  - qbittorrent
  - radarr
  - recyclarr
  - rustdesk
  - sabnzbd
  - sonarr
  - sonarr-nl
  - tautulli
  - tdarr
  - tracearr
