apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: descheduler
      version: 0.35.x
      sourceRef:
        kind: HelmRepository
        name: descheduler
        namespace: flux-system
      interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    kind: CronJob
    schedule: "*/15 * * * *"
    cronJobApiVersion: batch/v1
    successfulJobsHistory: 1
    failedJobsHistory: 1
    suspend: false
    tolerations:
      - key: node.cloudprovider.kubernetes.io/uninitialized
        operator: Exists
        effect: NoSchedule
      - key: intel.feature.node.kubernetes.io/gpu
        operator: Equal
        value: "true"
        effect: NoSchedule
    deschedulerPolicyAPIVersion: descheduler/v1alpha2
    deschedulerPolicy:
      profiles:
        - name: default
          pluginConfig:
            - name: DefaultEvictor
              args:
                evictLocalStoragePods: false
                evictSystemCriticalPods: false
                ignorePvcPods: false
                nodeFit: true
            - name: RemoveDuplicates
            - name: RemovePodsViolatingNodeTaints
            - name: RemovePodsViolatingNodeAffinity
              args:
                nodeAffinityType:
                  - requiredDuringSchedulingIgnoredDuringExecution
            - name: RemoveFailedPods
              args:
                reasons:
                  - NodeAffinity
                  - NodeShutdown
                  - UnexpectedAdmissionError
                includingInitContainers: true
                excludeOwnerKinds:
                  - Job
                minPodLifetimeSeconds: 3600
            - name: LowNodeUtilization
              args:
                thresholds:
                  cpu: 20
                  memory: 20
                  pods: 20
                targetThresholds:
                  cpu: 50
                  memory: 50
                  pods: 50
          plugins:
            balance:
              enabled:
                - RemoveDuplicates
                - LowNodeUtilization
            deschedule:
              enabled:
                - RemovePodsViolatingNodeTaints
                - RemovePodsViolatingNodeAffinity
                - RemoveFailedPods
