apiVersion: v1
kind: Namespace
metadata:
  name: tdarr
  labels:
    k10.kasten.io/backup: "true"
    k10.kasten.io/storage-class: vsphere
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: baseline
