apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clusterplex-config-vsan
  namespace: clusterplex
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsan
  resources:
    requests:
      storage: 10Gi
