---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sftpgo-secrets
  namespace: sftpgo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: sftpgo-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        SFTPGO_DEFAULT_ADMIN_USERNAME: admin
        SFTPGO_DEFAULT_ADMIN_PASSWORD: "{{ .adminPassword }}"
        SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_SECRET: "{{ .oidcClientSecret }}"
        SFTPGO_HTTPD__SIGNING_PASSPHRASE: "{{ .jwtKey }}"
        SFTPGO_DATA_PROVIDER__ENCRYPTION_KEY: "{{ .dataKey }}"
        # Consumed by plex-sync CronJob.
        PLEX_TOKEN: "{{ .plexToken }}"
  data:
    - secretKey: adminPassword
      remoteRef:
        key: SECRET_SFTPGO_ADMIN_PASSWORD
    - secretKey: oidcClientSecret
      remoteRef:
        key: SECRET_SFTPGO_OIDC_CLIENT_SECRET
    - secretKey: jwtKey
      remoteRef:
        key: SECRET_SFTPGO_JWT_SIGNING_KEY
    - secretKey: dataKey
      remoteRef:
        key: SECRET_SFTPGO_DATA_ENCRYPTION_KEY
    - secretKey: plexToken
      remoteRef:
        key: SECRET_PLEX_TOKEN
