---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: media-toolkit-secrets
  namespace: media-toolkit
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: media-toolkit-secrets
    creationPolicy: Owner
  data:
    - secretKey: SONARR_NL_API_KEY
      remoteRef:
        key: SECRET_SONARR_NL_API_KEY
    - secretKey: RADARR_NL_API_KEY
      remoteRef:
        key: SECRET_RADARR_NL_API_KEY
    - secretKey: TRUENAS_API_KEY
      remoteRef:
        key: SECRET_TRUENAS_API_KEY
