---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certs
  namespace: flux-system
spec:
  interval: 1h
  dependsOn:
    - name: cert-manager
    - name: external-secrets
  path: ./cluster-talos/kubernetes/infrastructure/core/cert-manager/certs/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
