apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-test-config
  namespace: nzbget-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsan
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-test-scratch
  namespace: nzbget-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsan
  resources:
    requests:
      storage: 200Gi
