---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tanzu-system-logging
  namespace: flux-system
spec:
  interval: 1h
  dependsOn:
    - name: configs
  path: ./cluster-talos/kubernetes/infrastructure/platform/tanzu-system-logging/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-vars
  wait: true
  timeout: 5m
