apiVersion: v1
kind: ConfigMap
metadata:
  name: boeye-ca-bundle
  namespace: vsphere-passthrough-node
data:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDezCCAmOgAwIBAgIQWoK2q7KvD4RK1RCkdoTFjzANBgkqhkiG9w0BAQsFADBE
    MRMwEQYKCZImiZPyLGQBGRYDbmV0MRUwEwYKCZImiZPyLGQBGRYFYm9leWUxFjAU
    BgNVBAMTDUJvZXllLUNBLTIwMjUwHhcNMjUxMTExMTM1MzM2WhcNNDAxMTExMTQw
    MzMxWjBEMRMwEQYKCZImiZPyLGQBGRYDbmV0MRUwEwYKCZImiZPyLGQBGRYFYm9l
    eWUxFjAUBgNVBAMTDUJvZXllLUNBLTIwMjUwggEiMA0GCSqGSIb3DQEBAQUAA4IB
    DwAwggEKAoIBAQCkNM/8Ac0KKOHJl+ai7PvMyPs2Zev83O6GEq+gYB795fMvlvEy
    qQ5d4fNW1d9Ih4FvGZ3rOP9qtMFSVdD4fYZnb+6TZKnECX7atDCsmNTWqc2M/3+3
    H2j64CvHQ/vEitx8vWmIhI29a/psbDgVKFCUojhX7ntyAzEn0TAY88P5/djdl9DK
    /2KRMG9cEYHG5RPOkPl/SLGVDk/Np81Bm+xukuM17Y4zNT6xx9IOqj22gKQk6EP/
    WrEC5eELrL7TF0XgQhbCOtb1DxlVJC+rVBjibJ82wzg9DHjV8jM+32iLwL9ZmPPY
    lgrsxrprdVQdaQ2cYtGlQd1c2cNMRvD7VaLNAgMBAAGjaTBnMBMGCSsGAQQBgjcU
    AgQGHgQAQwBBMA4GA1UdDwEB/wQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB0GA1Ud
    DgQWBBRgI7nh1rYFYh1nuXQA3yk530QjaDAQBgkrBgEEAYI3FQEEAwIBADANBgkq
    hkiG9w0BAQsFAAOCAQEAQmr8O0qa7iMYpfMgrJzYjL2QpkMWAjxgYM+CJvTHUfyZ
    6CLJvpRwZJdBKTtVhFAR12ps1Nwyb9mZS6kOCojTM+qmAo9WyI7EBS1hIDj2D5RV
    Sy9297UCO7JQ4cUjT+35IE6j7hrlEirovdr7dHjxZNBJRupjELaiV/Yes8OsaNuw
    3LPRVaCnV3vkj24Gou3aYpcIFDaMJeIjDRzVXF1+2DOg5gc5pdKMsGUyBOE6s+1p
    7Hju3JvzxR+w0R58YaK2zuJK9HeUY/DeHyQr8FSJdVDBzX6zzuFC6vduDi5KBIz8
    4vPdEg7bC4CTHe5GWoV2cK4LWAKUTf8nXlz6GeGOWQ==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIEzjCCAzagAwIBAgIJAOP2qHfXTr1vMA0GCSqGSIb3DQEBCwUAMIGCMREwDwYD
    VQQDDAhTS1ctVkNTQTEXMBUGCgmSJomT8ixkARkWB3ZzcGhlcmUxFTATBgoJkiaJ
    k/IsZAEZFgVsb2NhbDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWEx
    GzAZBgNVBAoMEnNrdy12Y3NhLmJvZXllLm5ldDAeFw0yNjA2MDYxMzU0NTdaFw0z
    NjA2MDMxMzU0NTdaMIGCMREwDwYDVQQDDAhTS1ctVkNTQTEXMBUGCgmSJomT8ixk
    ARkWB3ZzcGhlcmUxFTATBgoJkiaJk/IsZAEZFgVsb2NhbDELMAkGA1UEBhMCVVMx
    EzARBgNVBAgMCkNhbGlmb3JuaWExGzAZBgNVBAoMEnNrdy12Y3NhLmJvZXllLm5l
    dDCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBALD1HHN9CMwUnfcgQLc5
    m+jpMk2Gd36xR65b45GOwQKyKkD7o93MwUIfXzYOTZz8wW6183LjJrDAQBYtvF42
    kQ6XBFT6SKhl+23pcKDkpGW8P5fuW2NHu0fwyEM2jb+tWYF68TLoIND2Cws3n+NR
    11coeX51r5YwvYDcl2cgf7ZA4iJmxYkkC5WfLgVYjnBXrUsJYTqLXsxPE1LHU8yW
    9kAShpjBZa6iAiUBWDuNcG0VOxJ2SzrP8crC308Wiy+ez3NWsZZKCd0rYBCx4I8X
    X4/KEL5mZl1WytVvtmC1IXwX/r9AYqPOC6IXK3AW7LyqEexzBGfc9WUPWtgxXAFC
    ksMUavSAzO94wbKvqvju0buVpe6+Kp3SZVkzHRRAMH70O79LO8FYAK9UZy52fOs3
    1xPIRc5c6ja9bGByjQwW5LaqZ3++fJtgaJjUAwT6XlH65RTCgqDwwj7ugHuR8dbb
    1r1UryrQpYFSxXLgC/3oqXq608YgbxLZEhDe9rgiFb2LswIDAQABo0UwQzAdBgNV
    HQ4EFgQUD2x1uOa0QmXtaAejku4DmxvPEzkwDgYDVR0PAQH/BAQDAgEGMBIGA1Ud
    EwEB/wQIMAYBAf8CAQAwDQYJKoZIhvcNAQELBQADggGBAEgPqdtePie5DEgQJnV+
    XWkC5Xf8q92dsIQo/MGgLikWygzKX/+IVrFoNo5g3EFv6kSO2kM5vP0/TfMeIQH5
    5FEHoxpb4AHz9NVJOxOwVDsB1/AluyF3iya9EtmtoZROvB5BUywD62D1ghpWidkk
    XcTGNzUO+mkIUVEBvw3L78bq+ZptTAlzlMVhB61jkBOca6S3AYPHIo2mzb3oPUzl
    JS5mS3DQQYGFJ4igMV5Fvj9XrR+f2HEFRZM3P0sVJqQ5SwQwoWpRykfhsrmjm7qw
    F4qHm8jEFFdIlDF2wXmfa3hmOhKSSe00xM4QBtlgm210si450H46exen1rcJB8d+
    o8u4Z6/QIRNes6WpwLwzYp7HnjI95b5NxAWW8pdxXv0PqNSKBQEjggg/8iVGp7N6
    0iB2pu/whK9xN15IaUBUBMYbtthUNc9dVhXPz+JLEhkffBL+bllwuz4kjpQzBy+7
    GLBbzxtr7VrNTMe89hZMZTSZMW6BOASwZ0f5CV3m+jbMHw==
    -----END CERTIFICATE-----
