apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vsphere-credentials
  namespace: gpu-node-vsphere-maintenance
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: vsphere-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        VCENTER_HOST: "skw-vcsa.${SECRET_DOMAIN}"
        VCENTER_USER: "{{ .username }}"
        VCENTER_PASSWORD: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: SECRET_VSPHERE_USERNAME
    - secretKey: password
      remoteRef:
        key: SECRET_VSPHERE_PASSWORD
