apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: b2-etcd-backup-creds
  namespace: etcd-backup
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: b2-etcd-backup-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: "{{ .keyId }}"
        AWS_SECRET_ACCESS_KEY: "{{ .appKey }}"
  data:
    - secretKey: keyId
      remoteRef:
        key: SECRET_B2_ETCD_KEY_ID
    - secretKey: appKey
      remoteRef:
        key: SECRET_B2_ETCD_APP_KEY
