apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ip-pool.yaml
  - bgp-cluster-config.yaml
  - bgp-peer-config.yaml
  - bgp-advertisement.yaml
  - gateway-class.yaml
  - gateway.yaml
  - certificate-wildcard.yaml
  - httproute-http-redirect.yaml
  - httproute-hubble.yaml
