---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-github-webhook-token
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: flux-github-webhook-token
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        key: SECRET_FLUX_GITHUB_WEBHOOK_TOKEN
