---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-tunnel
  namespace: flux-system
spec:
  interval: 1h
  dependsOn:
    - name: cloudflare-operator
    - name: configs
  path: ./cluster-talos/kubernetes/infrastructure/platform/cloudflare-operator-system/cloudflare-tunnel/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-vars
      - kind: Secret
        name: cloudflare-substvars
  wait: true
  timeout: 5m
