apiVersion: v1
kind: ConfigMap
metadata:
  name: boeye-ca-bundle
  namespace: gpu-node-vsphere-maintenance
data:
  ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDezCCAmOgAwIBAgIQWoK2q7KvD4RK1RCkdoTFjzANBgkqhkiG9w0BAQsFADBE
    MRMwEQYKCZImiZPyLGQBGRYDbmV0MRUwEwYKCZImiZPyLGQBGRYFYm9leWUxFjAU
    BgNVBAMTDUJvZXllLUNBLTIwMjUwHhcNMjUxMTExMTM1MzM2WhcNNDAxMTExMTQw
    MzMxWjBEMRMwEQYKCZImiZPyLGQBGRYDbmV0MRUwEwYKCZImiZPyLGQBGRYFYm9l
    eWUxFjAUBgNVBAMTDUJvZXllLUNBLTIwMjUwggEiMA0GCSqGSIb3DQEBAQUAA4IB
    DwAwggEKAoIBAQCkNM/8Ac0KKOHJl+ai7PvMyPs2Zev83O6GEq+gYB795fMvlvEy
    qQ5d4fNW1d9Ih4FvGZ3rOP9qtMFSVdD4fYZnb+6TZKnECX7atDCsmNTWqc2M/3+3
    H2j64CvHQ/vEitx8vWmIhI29a/psbDgVKFCUojhX7ntyAzEn0TAY88P5/djdl9DK
    /2KRMG9cEYHG5RPOkPl/SLGVDk/Np81Bm+xukuM17Y4zNT6xx9IOqj22gKQk6EP/
    WrEC5eELrL7TF0XgQhbCOtb1DxlVJC+rVBjibJ82wzg9DHjV8jM+32iLwL9ZmPPY
    lgrsxrprdVQdaQ2cYtGlQd1c2cNMRvD7VaLNAgMBAAGjaTBnMBMGCSsGAQQBgjcU
    AgQGHgQAQwBBMA4GA1UdDwEB/wQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB0GA1Ud
    DgQWBBRgI7nh1rYFYh1nuXQA3yk530QjaDAQBgkrBgEEAYI3FQEEAwIBADANBgkq
    hkiG9w0BAQsFAAOCAQEAQmr8O0qa7iMYpfMgrJzYjL2QpkMWAjxgYM+CJvTHUfyZ
    6CLJvpRwZJdBKTtVhFAR12ps1Nwyb9mZS6kOCojTM+qmAo9WyI7EBS1hIDj2D5RV
    Sy9297UCO7JQ4cUjT+35IE6j7hrlEirovdr7dHjxZNBJRupjELaiV/Yes8OsaNuw
    3LPRVaCnV3vkj24Gou3aYpcIFDaMJeIjDRzVXF1+2DOg5gc5pdKMsGUyBOE6s+1p
    7Hju3JvzxR+w0R58YaK2zuJK9HeUY/DeHyQr8FSJdVDBzX6zzuFC6vduDi5KBIz8
    4vPdEg7bC4CTHe5GWoV2cK4LWAKUTf8nXlz6GeGOWQ==
    -----END CERTIFICATE-----
