---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-node-vsphere-maintenance-controller
  namespace: gpu-node-vsphere-maintenance
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: gpu-node-vsphere-maintenance-controller
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    vcenter:
      existingSecret: vsphere-credentials
      caBundle:
        configMapName: boeye-ca-bundle
