---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: octodns-netbox
  namespace: octodns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: octodns-netbox
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        NETBOX_API_TOKEN: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: SECRET_NETBOX_ADMIN_TOKEN
