---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-crds
  namespace: flux-system
spec:
  interval: 1h
  path: ./cluster-talos/kubernetes/infrastructure/controllers/gateway-api
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-controllers
  namespace: flux-system
spec:
  interval: 1h
  dependsOn:
    - name: infrastructure-crds
  path: ./cluster-talos/kubernetes/infrastructure/controllers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-certs
  namespace: flux-system
spec:
  interval: 1h
  dependsOn:
    - name: infrastructure-controllers
  path: ./cluster-talos/kubernetes/infrastructure/certs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-configs
  namespace: flux-system
spec:
  interval: 1h
  dependsOn:
    - name: infrastructure-controllers
    - name: infrastructure-certs
  path: ./cluster-talos/kubernetes/infrastructure/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-renovate
  namespace: flux-system
spec:
  interval: 1h
  dependsOn:
    - name: infrastructure-configs
  path: ./cluster-talos/kubernetes/infrastructure/renovate
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
