---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netbox
  namespace: flux-system
spec:
  interval: 1h
  dependsOn:
    - name: cnpg
  path: ./cluster-talos/kubernetes/apps/tools/netbox/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-vars
