---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gpu-exporter
  labels:
    app.kubernetes.io/name: intel-gpu-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: intel-gpu-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: intel-gpu-exporter
      annotations: {}
    spec:
      hostPID: true
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
      tolerations:
        - key: intel.feature.node.kubernetes.io/gpu
          operator: Equal
          value: "true"
          effect: PreferNoSchedule
      containers:
        - name: exporter
          image: python:3.14-alpine@sha256:dd4d2bd5b53d9b25a51da13addf2be586beebd5387e289e798e4083d94ca837a
          command: ["python", "-u", "/app/exporter.py"]
          env:
            - name: SAMPLE_INTERVAL_SEC
              value: "5"
          ports:
            - name: http-metrics
              containerPort: 8080
              protocol: TCP
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 128Mi
          volumeMounts:
            - name: script
              mountPath: /app
              readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
      volumes:
        - name: script
          configMap:
            name: intel-gpu-exporter-script
        - name: sys
          hostPath:
            path: /sys
            type: Directory
