---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      plex:
        replicas: 1
        pod:
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
          tolerations:
            - key: "intel.feature.node.kubernetes.io/gpu"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"
          securityContext:
            supplementalGroups: [568]
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/plex
              tag: "1.43.1.10611-1e34174b1-ls302"
            env:
              TZ: Europe/Brussels
              VERSION: docker
              PUID: "1000"
              PGID: "1000"
              UMASK_SET: "002"
            resources:
              limits:
                gpu.intel.com/i915: 1

    service:
      plex:
        controller: plex
        ports:
          http:
            port: 32400
      plex-lb:
        type: LoadBalancer
        controller: plex
        externalTrafficPolicy: Local
        annotations:
          io.cilium/lb-ipam-ips: "172.16.4.104"
          external-dns.alpha.kubernetes.io/hostname: "plex-web.${SECRET_DOMAIN}"
        ports:
          http:
            port: 32400
      plex-public:
        type: ExternalName
        externalName: skw.wan.${SECRET_DOMAIN}
        annotations:
          external-dns.alpha.kubernetes.io/hostname: plex.${SECRET_DOMAIN}
          external-dns.alpha.kubernetes.io/public: "true"
        ports:
          http:
            port: 32400

    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Plex
          gethomepage.dev/description: Media server
          gethomepage.dev/group: Media
          gethomepage.dev/icon: plex.png
          gethomepage.dev/href: https://plex.${SECRET_DOMAIN}
        hostnames:
          - "plex.${SECRET_DOMAIN}"
        parentRefs:
          - name: main
            namespace: cilium
            sectionName: https
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: plex
                port: http

    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: plex-config-pms
        advancedMounts:
          plex:
            app:
              - path: /config
      transcode:
        type: nfs
        server: ${SECRET_NFS_HOST}.${SECRET_DOMAIN}
        path: /mnt/SSD/mediapool/plextranscode
        advancedMounts:
          plex:
            app:
              - path: /transcode
      media:
        type: nfs
        server: ${SECRET_NFS_HOST}.${SECRET_DOMAIN}
        path: /mnt/DATA/mediapool/media
        advancedMounts:
          plex:
            app:
              - path: /media
      backup:
        type: nfs
        server: ${SECRET_NFS_HOST}.${SECRET_DOMAIN}
        path: /mnt/DATA/backup/plex
        advancedMounts:
          plex:
            app:
              - path: /backup
