---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: intel.feature.node.kubernetes.io/gpu
                    operator: DoesNotExist
      tolerations:
        - key: node.cloudprovider.kubernetes.io/uninitialized
          operator: Exists
          effect: NoSchedule
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        supplementalGroups: [568]
        seccompProfile:
          type: RuntimeDefault
    controllers:
      qbittorrent:
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/qbittorrent
              tag: 5.1.4-r3-ls452
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Brussels
    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: 8080
      bittorrent-tcp:
        controller: qbittorrent
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 172.16.4.108
          io.cilium/lb-ipam-sharing-key: qbittorrent
        externalTrafficPolicy: Local
        ports:
          bittorrent-tcp:
            port: 6881
            protocol: TCP
      bittorrent-udp:
        controller: qbittorrent
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 172.16.4.108
          io.cilium/lb-ipam-sharing-key: qbittorrent
        externalTrafficPolicy: Local
        ports:
          bittorrent-udp:
            port: 6881
            protocol: UDP
    route:
      app:
        annotations:
          gatus.home-operations.com/endpoint: |
            conditions: ["[STATUS] < 500"]
            interval: 60s
            group: arr
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: qBittorrent
          gethomepage.dev/description: Torrent downloader
          gethomepage.dev/group: Downloaders
          gethomepage.dev/weight: "20"
          gethomepage.dev/icon: qbittorrent.png
          gethomepage.dev/href: https://qbittorrent.${SECRET_DOMAIN}
          gethomepage.dev/widget.type: qbittorrent
          gethomepage.dev/widget.url: http://qbittorrent-app.qbittorrent.svc:8080
          gethomepage.dev/widget.username: homepage
          gethomepage.dev/widget.password: homepage
        hostnames:
          - qbittorrent.${SECRET_DOMAIN}
        parentRefs:
          - name: main
            namespace: cilium
            sectionName: https
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: app
                port: http
    persistence:
      run:
        type: emptyDir
        medium: Memory
        globalMounts:
          - path: /run
      config:
        type: persistentVolumeClaim
        existingClaim: qbittorrent-config
        globalMounts:
          - path: /config
      media:
        type: nfs
        server: ${SECRET_NFS_HOST}.${SECRET_DOMAIN}
        path: /mnt/DATA/mediapool
        globalMounts:
          - path: /mnt/skw-truenas-data
