apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: qbittorrent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsan
  resources:
    requests:
      storage: 10Gi
