---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metrics-server/ks.yaml
  - reloader/ks.yaml
  - descheduler/ks.yaml
  - cnpg-system/ks.yaml
  - monitoring/ks.yaml
  - configs/ks.yaml
  - external-dns/external-dns/ks.yaml
  - external-dns/external-dns-cloudflare/ks.yaml
  - cloudflare-operator-system/cloudflare-operator/ks.yaml
  - cloudflare-operator-system/cloudflare-tunnel/ks.yaml
  - longhorn-system/ks.yaml
  - tanzu-system-logging/ks.yaml
  - kasten-io/ks.yaml
  - spegel/ks.yaml
  - renovate/ks.yaml
