apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vsphere-cloud-secret
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: vsphere-cloud-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        skw-vcsa.${SECRET_DOMAIN}.username: "{{ .username }}"
        skw-vcsa.${SECRET_DOMAIN}.password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: SECRET_VSPHERE_USERNAME
    - secretKey: password
      remoteRef:
        key: SECRET_VSPHERE_PASSWORD
