apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vsphere-cpi-config
  namespace: vmware-system-cpi
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: vsphere-cpi-config
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        vsphere.conf: |
          global:
            port: 443
            insecureFlag: true
          vcenter:
            skw-vcsa.${SECRET_DOMAIN}:
              server: skw-vcsa.${SECRET_DOMAIN}
              user: "{{ .username }}"
              password: "{{ .password }}"
              datacenters:
                - SKW
  data:
    - secretKey: username
      remoteRef:
        key: SECRET_VSPHERE_USERNAME
    - secretKey: password
      remoteRef:
        key: SECRET_VSPHERE_PASSWORD
