apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clusterplex-config
  namespace: clusterplex
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
