apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vsan
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - discard
parameters:
  storagepolicyname: "SKW-VSAN-Stripe"
