apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vsphere-config-secret
  namespace: vmware-system-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: vsphere-config-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        csi-vsphere.conf: |
          [Global]
          cluster-id = "k8s-talos"
          user = "{{ .username }}"
          password = "{{ .password }}"
          [VirtualCenter "skw-vcsa.${SECRET_DOMAIN}"]
          datacenters = "SKW"
          insecure-flag = "true"
  data:
    - secretKey: username
      remoteRef:
        key: SECRET_VSPHERE_USERNAME
    - secretKey: password
      remoteRef:
        key: SECRET_VSPHERE_PASSWORD
