---
apiVersion: v1
kind: Namespace
metadata:
  name: be-stream-downloader
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: baseline
    k10.kasten.io/backup: "true"
    k10.kasten.io/storage-class: vsphere
