---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: network-health-state
  namespace: monitoring
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 64Mi
