---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway-api/ks.yaml
  - cilium/ks.yaml
  - kubelet-csr-approver/ks.yaml
  - metrics-server/ks.yaml
  - snapshot-controller/ks.yaml
  - vsphere-cpi/ks.yaml
  - vsphere-csi/ks.yaml
  - descheduler/ks.yaml
  - intel-gpu/ks.yaml
  - intel-gpu-config/ks.yaml
  - reloader/ks.yaml
  - etcd-backup/ks.yaml
  - gpu-node-vsphere-maintenance/ks.yaml
  - cert-manager/cert-manager/ks.yaml
  - cert-manager/certs/ks.yaml
  - external-secrets/ks.yaml
