---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smtp2graph-config
  namespace: smtp
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: smtp2graph-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yml: |
          mode: full
          send:
            appReg:
              tenant: "{{ .TENANT_ID }}"
              id: "{{ .CLIENT_ID }}"
              secret: "{{ .CLIENT_SECRET }}"
            forceMailbox: Frank@boeye.net
          receive:
            port: 25
            ipWhitelist:
              - 127.0.0.0/8
              - 10.244.0.0/16
              - 172.16.0.0/16
            maxSize: 25m
  data:
    - secretKey: TENANT_ID
      remoteRef:
        key: SECRET_SMTP_RELAY_TENANT_ID
    - secretKey: CLIENT_ID
      remoteRef:
        key: SECRET_SMTP_RELAY_CLIENT_ID
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: SECRET_SMTP_RELAY_CLIENT_SECRET
