---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vcfops-collector
  namespace: vcfops-collector
---
apiVersion: v1
kind: Secret
metadata:
  name: vcfops-collector-token
  namespace: vcfops-collector
  annotations:
    kubernetes.io/service-account.name: vcfops-collector
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vcfops-collector
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [nodes/metrics, nodes/stats, nodes/proxy, nodes/spec, pods/log]
    verbs: [get, list]
  - nonResourceURLs: ["*"]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vcfops-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vcfops-collector
subjects:
  - kind: ServiceAccount
    name: vcfops-collector
    namespace: vcfops-collector
