apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - autobrr/ks.yaml
  - bazarr/ks.yaml
  - neutarr/ks.yaml
  - prowlarr/ks.yaml
  - radarr/ks.yaml
  - recyclarr/ks.yaml
  - sonarr/ks.yaml
  - sonarr-nl/ks.yaml
