---
name: flux-diff

on:
  pull_request:
    branches: ["main"]
    paths:
      - "cluster-talos/kubernetes/**"
      - ".github/workflows/flux-diff.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  diff:
    name: flux-local diff
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        resource: ["helmrelease", "kustomization"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install flux
        uses: fluxcd/flux2/action@main

      - name: Diff ${{ matrix.resource }}
        uses: allenporter/flux-local/action/diff@8.2.0
        id: diff
        with:
          path: cluster-talos/kubernetes
          resource: ${{ matrix.resource }}
          live-branch: main
          sources: flux-system=cluster-talos/kubernetes

      - name: PR comment
        if: ${{ steps.diff.outputs.diff != '' }}
        uses: mshick/add-pr-comment@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message-id: flux-diff/${{ matrix.resource }}
          message-failure: flux-local diff failed
          message: |
            `${{ matrix.resource }}` diff:
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
