---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postfix-relay-smtp
  namespace: postfix-relay
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: postfix-relay-smtp
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RELAYHOST_USERNAME: "{{ .SMTP_USERNAME }}"
        RELAYHOST_PASSWORD: "{{ .SMTP_PASSWORD }}"
  data:
    - secretKey: SMTP_USERNAME
      remoteRef:
        key: SECRET_SMTP_USERNAME
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: SECRET_SMTP_PASSWORD
