---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postfix-relay
  namespace: postfix-relay
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      postfix:
        replicas: 1
        strategy: Recreate
        containers:
          app:
            image:
              repository: docker.io/boky/postfix
              tag: v5.1.0-alpine
            env:
              RELAYHOST: smtp.office365.com:587
              ALLOWED_SENDER_DOMAINS: ${SECRET_DOMAIN}
              POSTFIX_myhostname: smtp.${SECRET_DOMAIN}
              POSTFIX_smtp_tls_security_level: encrypt
              POSTFIX_smtp_sasl_mechanism_filter: login
              POSTFIX_smtp_destination_rate_delay: 1s
              POSTFIX_mynetworks: 127.0.0.0/8 10.244.0.0/16 172.16.0.0/16
            envFrom:
              - secretRef:
                  name: postfix-relay-smtp
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 25
                  initialDelaySeconds: 30
                  periodSeconds: 30
              readiness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 25
                  initialDelaySeconds: 10
                  periodSeconds: 10
              startup:
                enabled: false
            resources:
              requests:
                cpu: 40m
                memory: 40Mi
              limits:
                memory: 100Mi

    service:
      app:
        controller: postfix
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 172.16.4.105
          external-dns.alpha.kubernetes.io/hostname: smtp.${SECRET_DOMAIN}
        ports:
          smtp:
            port: 25
            targetPort: 25

    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: intel.feature.node.kubernetes.io/gpu
                    operator: DoesNotExist
