---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whisper-asr
  namespace: whisper-asr
spec:
  interval: 30m
  install:
    timeout: 15m
    remediation:
      retries: 2
  upgrade:
    timeout: 15m
    remediation:
      retries: 2
  chart:
    spec:
      chart: app-template
      version: 5.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      whisper-asr:
        containers:
          app:
            image:
              repository: onerahmet/openai-whisper-asr-webservice
              tag: v1.10.0@sha256:0616c3d5fc6924e9d59aa8a7a3a944fbe8f3a5d701e5fc1fa2ce5b933dfecb73
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Brussels
              ASR_ENGINE: faster_whisper
              ASR_MODEL: small
            resources:
              requests:
                cpu: 250m
                memory: 2Gi
              limits:
                cpu: "2"
    service:
      app:
        controller: whisper-asr
        ports:
          http:
            port: 9000
    persistence:
      cache:
        existingClaim: whisper-asr-cache
        globalMounts:
          - path: /root/.cache
