---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whisper-asr
  namespace: whisper-asr
spec:
  interval: 30m
  install:
    timeout: 20m
    remediation:
      retries: 2
  upgrade:
    timeout: 20m
    remediation:
      retries: 2
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
    controllers:
      whisper-asr:
        containers:
          app:
            image:
              repository: ventura8/whisper-pro-asr
              tag: 1.0.4@sha256:68fa1512e3529d57bcf583707276812267143f4bed16e4e4463a0c1e84c3150f
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/Brussels
              ASR_DEVICE: CPU
              ASR_PREPROCESS_DEVICE: CPU
              ASR_MODEL: Systran/faster-whisper-medium
              ASR_BEAM_SIZE: "5"
              ASR_THREADS: "4"
              FFMPEG_HWACCEL: none
              WHISPER_TEMP_DIR: /tmp/whisper
            resources:
              requests:
                cpu: "2"
                memory: 4Gi
              limits:
                cpu: "6"
                memory: 8Gi
    service:
      app:
        controller: whisper-asr
        ports:
          http:
            port: 9000
    persistence:
      cache:
        existingClaim: whisper-asr-cache
        globalMounts:
          - path: /app/model_cache
      tmp-whisper:
        type: emptyDir
        medium: Memory
        sizeLimit: 2Gi
        globalMounts:
          - path: /tmp/whisper
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
