---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-asr-cache
  namespace: whisper-asr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
